### ISSUE TITLE
When using ParentClass's __init__ method, why pass in parents' argument too ? 

### ISSUE THREAD

**Issue by johnhhu2020** [DidiMilikina/DataCamp#1]
Hello, I saw your sharing, it's great finding some useful studying material with so many code samples. Thank you.

Here I was confused on DataCamp Data Engineering with Python course, can you please help me clarify it? The inheritance question ######

```
jhu@debian:~/datacmap_data_engineering$ cat text_analyzer/social_media.py 
from text_analyzer import Document
from collections import Counter


# Define a SocialMedia class that is a child of the `Document class`
class SocialMedia(Document):
    def __init__(self, text):
        Document.__init__(self, text)          ######## ???? Here, why we pass 'text' too???
        self.hashtag_counts = self._count_hashtags()
        self.mention_counts = self._count_mentions()

    def _count_hashtags(self):
        # Filter attribute so only words starting with '#' remain
        return SocialMedia.filter_word_counts(self.word_counts, first_char='#')  

    def _count_mentions(self):
        # Filter attribute so only words starting with '@' remain
        return SocialMedia.filter_word_counts(self.word_counts, first_char='@')

```

**Comment by DidiMilikina** [comment]
Hello!

If we take into consideration the following exercise: https://github.com/DidiMilikina/DataCamp/blob/master/Data%20Engineer%20with%20Python/03.%20Software%20Engineering%20for%20Data%20Scientists%20in%20Python/03.%20Utilizing%20Classes/06.%20Adding%20functionality%20to%20a%20child%20class.py

In the description, they mentioned:
_For reference, the definition of Document can be seen below.
class Document:
    # Initialize a new Document instance
    def __init__(self, text):
        **self.text = text
        # Pre tokenize the document with non-public tokenize method
        self.tokens = self._tokenize()
        # Pre tokenize the document with non-public count_words
        self.word_counts = self._count_words()**
    def _tokenize(self):
        return tokenize(self.text)
    # Non-public method to tally document's word counts
    def _count_words(self):
        # Use collections.Counter to count the document's tokens
        return Counter(self.tokens)_

By definition, the class Document has init function, which has self and text as parameters that are also used in the function's body. 
In order to inherit the entire functionality of the class Document, we need to pass these two arguments in 

class SocialMedia(Document):
    def __init__(self, text):
        **Document.__init__(self, text)**         
        self.hashtag_counts = self._count_hashtags()
        self.mention_counts = self._count_mentions()

I hope this helps you! 

PS: I tried to search for that exercise in the DataCamp courses, but I ended my subscription, and it seems that they changed the courses. Therefore, I cannot check whether this is the full description of the exercise.

Best wishes,
Didi Milikina

**Comment by DidiMilikina** [comment]
Hello!

If we take into consideration the following exercise: https://github.com/DidiMilikina/DataCamp/blob/master/Data%20Engineer%20with%20Python/03.%20Software%20Engineering%20for%20Data%20Scientists%20in%20Python/03.%20Utilizing%20Classes/06.%20Adding%20functionality%20to%20a%20child%20class.py

In the description, they mentioned:
```
For reference, the definition of Document can be seen below.
class Document:
     Initialize a new Document instance
    def __init__(self, text):
        self.text = text
        # Pre tokenize the document with non-public tokenize method
        self.tokens = self._tokenize()
        # Pre tokenize the document with non-public count_words
        self.word_counts = self._count_words()
```

By definition, the class Document has init method, which has self and text as parameters that are also used in the method's body.
In order to inherit the entire functionality of the class Document, we need to pass these two arguments in

```
Define a SocialMedia class that is a child of the `Document class`
class SocialMedia(Document):
    def __init__(self, text):
        Document.__init__(self, text) <- here
        self.hashtag_counts = self._count_hashtags()*     
```

The following article can give you more insights about encapsulation in Python: https://www.geeksforgeeks.org/encapsulation-in-python/?ref=lbp


I hope this helps you!

PS: I tried to search for that exercise in the DataCamp courses, but I ended my subscription, and it seems that they changed the courses. Therefore, I cannot check whether this is the full description of the exercise.

Best wishes,
Didi Milikina

**Comment by johnhhu2020** [comment]
Thank you very much. This was the first time I heard "encapsulation"

**Comment by johnhhu2020** [comment]
"By definition, the class Document has init method, which has self and text as parameters that are also used in the method's body.
In order to inherit the entire functionality of the class Document, we need to pass these two arguments in"
